function Hd = ChebyI
%CHEBYI Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
% Generated on: 26-Mar-2024 18:06:52

% Chebyshev Type I Lowpass filter designed using FDESIGN.LOWPASS.
% sampling freq (Hz)
fs = 44100; 

% passband freq (Hz)
Fpass = 4900;        

% stopband freq (Hz)
Fstop = 5512.5;    

% passband ripple (dB)
Apass = 5;           

% stopband attenuation (dB)
Astop = 40;         

match = 'passband';  

h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, fs);
Hd = design(h, 'cheby1', 'MatchExactly', match);

% [EOF]
