function Hd = Elliptic
%ELLIPTIC Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
% Generated on: 26-Mar-2024 18:06:38

% Elliptic Bandstop filter designed using FDESIGN.BANDSTOP.
% sampling freq (Hz)
fs = 44100; 

% 1st passband freq (Hz)
Fpass1 = 6300;    

% 1st stopband freq (Hz)
Fstop1 = 7350;    

% 2nd stopband frew (Hz)
Fstop2 = 14700;   

% 2nd passband freq (Hz)
Fpass2 = 17640;   

% 1st passband ripple (dB)
Apass1 = 1;       

% 2nd passband ripple (dB)
Apass2 = 1;       

% stopband attenuation (dB)
Astop  = 50;     

match  = 'both';  
h  = fdesign.bandstop(Fpass1, Fstop1, Fstop2, Fpass2, Apass1, Astop, ...
                      Apass2, fs);
Hd = design(h, 'ellip', 'MatchExactly', match);

% [EOF]
